GET http://localhost:3000/users HTTP/1.1

###
GET http://localhost:3000/users/66d82a1f4add928e702debec HTTP/1.1

###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "email": "a@a.com",
  "password": "1234"
}

###
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "Product_name": "Mouse",
  "Product_type": "PC accesory",
  "Product_stock": 1234,
  "Product_price": 5678
}

###
PUT http://localhost:3000/users/66d82a1f4add928e702debec HTTP/1.1
Content-Type: application/json

{
  "name": "Jane",
  "email": "b@b.com",
  "password": "4321"
}

###
DELETE http://localhost:3000/users/66d82a1f4add928e702debec HTTP/1.1